apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cc-final
  labels:
    app: cc-final
spec:
  template:
    metadata:
      labels:
        app: cc-final
    spec:
      containers:
        - name: cc-final
          image: gcr.io/cc-final-296102/cc-final:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: dbname
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command: [ "/cloud_sql_proxy",
                     "-instances=cc-final-296102:us-east4:cc-final-database=tcp:3306",
                     "-credential_file=/secrets/cloudsql/sql_credentials.json"]
          volumeMounts:
          - name: my-secrets-volume
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
      - name: my-secrets-volume
        secret:
          secretName: cloudsql-instance-credentials
