apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cc-final
  name: cc-final
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cc-final
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cc-final
    spec:
      containers:
        - name: cc-final
          image: gcr.io/cc-final-296102/cc-final:v1
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: dbname
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=cc-final-296102:us-east4:cc-final-database=tcp:3306"
            - "-credential_file=/secrets/sql_credentials.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
          - name: my-secrets-volume
            mountPath: /secrets/
            readOnly: true
      volumes:
      - name: my-secrets-volume
        secret:
          secretName: cloudsql-instance-credentials
