apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: randomizer
  name: randomizer
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: randomizer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: randomizer
    spec:
      containers:
        - image: gcr.io/cc-final-296102/github.com/neppney/test-cc-final
          imagePullPolicy: Always
          name: randomizer
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: dbname
        - name: cloudsql-proxy
            image: gcr.io/cloudsql-docker/gce-proxy:1.16
            command: [ "/cloud_sql_proxy",
                       "-instances=<cc-final-296102:us-east4:cc-final-database>=tcp:3306",
                       "-credential_file=/secrets/cloudsql/sql_credentials.json" ]
            volumeMounts:
              - name: my-secrets-volume
                mountPath: /secrets/cloudsql
                readOnly: true
            volumes:
              - name: my-secrets-volume
                secret:
                  secretName: cloudsql-instance-credentials
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: randomizer
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: randomizer
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: randomizer
  name: app-service
  namespace: default
spec:
  clusterIP: 10.3.243.33
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31808
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: randomizer
  sessionAffinity: None
  type: LoadBalancer
